language: minimal
dist: xenial
branches:
  only:
    - master
addons:
  apt:
    packages:
      - latexmk
      - texlive-bibtex-extra
      - texlive-full
script:
  - mkdir pdf
  - latexmk -pdf
  - mv *.pdf pdf
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: pdf
  github_token: $GITHUB_TOKEN
